from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Optional

from supabase import Client, create_client

from postgrest.exceptions import APIError

from config import settings
from logging_config import logger

# -------------------------------------------------------------------------
# Client singleton (lazy-init)
# ---------------------------------------------------------------------------

# The supabase client can raise deep import-time errors when package
# versions are incompatible (e.g. httpx/gotrue/supabase mismatches). To
# ensure the app can surface a clear error and to avoid import-time
# crashes during container startup, create the client lazily on first use.
supabase: Optional[Client] = None


def get_supabase() -> Client:
    """Return a singleton Supabase client, creating it on first use.

    Raises a RuntimeError with an actionable message when initialization
    fails due to dependency incompatibilities.
    """
    global supabase
    if supabase is not None:
        return supabase
    try:
        supabase = create_client(
            settings.SUPABASE_URL,
            settings.SUPABASE_SERVICE_ROLE_KEY,
        )
        return supabase
    except TypeError as exc:
        logger.error("Supabase client init failed (TypeError)", exc_info=exc)
        raise RuntimeError(
            "Supabase client initialization failed. This often indicates an "
            "incompatible set of packages (supabase / gotrue / httpx). "
            "Ensure httpx>=0.28.0 is installed — gotrue>=2.9 uses the proxy= "
            "kwarg which was added in httpx 0.28.0."
        ) from exc
    except Exception as exc:
        logger.error("Supabase client init failed", exc_info=exc)
        raise
# Resolved once at import time; override with DB_TABLE_NAME in .env
_TABLE: str = settings.DB_TABLE_NAME

# PostgREST error codes that indicate a permanent misconfiguration
_FATAL_PGRST_CODES = {"PGRST205", "PGRST200", "PGRST106"}


# ---------------------------------------------------------------------------
# Product creation
# ---------------------------------------------------------------------------


async def create_product(
    title: str = "",
    jewellery_type: str = "",
) -> dict:
    """
    Insert a new row into the products table and return it.
    ``id`` and ``created_at`` are generated by Supabase.
    """
    payload: dict = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "title": title or "",  # always include title to satisfy NOT NULL
        "jewellery_type": jewellery_type or None,
    }

    try:
        resp = get_supabase().table(_TABLE).insert(payload).execute()
        product = resp.data[0]
        logger.info("Created product", extra={"product_id": product["id"]})
        return product
    except Exception as exc:
        logger.error("create_product failed", exc_info=exc)
        raise


# ---------------------------------------------------------------------------


async def fetch_pending_job() -> Optional[dict]:
    """
    Atomically claim one pending job by transitioning its status to
    'processing'.  Uses an optimistic-lock pattern:

      1. SELECT the oldest pending job (by created_at).
      2. UPDATE it to 'processing' only while it is still 'pending'
         — this guards against two workers claiming the same row.

    Returns the claimed job dict, or None when the queue is empty or
    another worker won the race.
    """
    try:
        # ── Step 1: find the oldest pending job ──────────────────────────
        select_resp = (
            get_supabase().table(_TABLE)
            .select("id")
            .eq("status", "pending")
            .order("created_at", desc=False)
            .limit(1)
            .execute()
        )

        if not select_resp.data:
            return None

        job_id: str = select_resp.data[0]["id"]

        # ── Step 2: claim it atomically with an optimistic lock ───────────
        now = datetime.now(timezone.utc).isoformat()
        update_resp = (
            get_supabase().table(_TABLE)
            .update({"status": "processing", "processing_started_at": now})
            .eq("id", job_id)
            .eq("status", "pending")   # only succeeds if still pending
            .execute()
        )

        if not update_resp.data:
            # Another worker claimed it first — harmless contention
            return None

        job = update_resp.data[0]
        logger.info("Claimed job", extra={"job_id": job_id})
        return job

    except APIError as exc:
        if exc.code in _FATAL_PGRST_CODES:
            # Re-raise so the worker can apply a long back-off instead of
            # hammering Supabase with requests every 2 seconds.
            raise
        logger.error("fetch_pending_job API error", exc_info=exc)
        return None
    except Exception as exc:
        logger.error("fetch_pending_job failed", exc_info=exc)
        return None


async def fetch_job_by_id(job_id: str) -> Optional[dict]:
    """Return a full job row by primary key, or None if not found."""
    try:
        resp = (
            get_supabase().table(_TABLE)
            .select("*")
            .eq("id", job_id)
            .limit(1)
            .execute()
        )
        return resp.data[0] if resp.data else None

    except Exception as exc:
        logger.error(
            "fetch_job_by_id failed",
            extra={"job_id": job_id},
            exc_info=exc,
        )
        return None


async def reset_stale_jobs(timeout_seconds: int) -> int:
    """
    Detect jobs stuck in 'processing' beyond *timeout_seconds* and
    reset them to 'pending' so the worker will retry them.

    Returns the number of rows reset.
    """
    try:
        cutoff = (
            datetime.now(timezone.utc) - timedelta(seconds=timeout_seconds)
        ).isoformat()

        resp = (
            get_supabase().table(_TABLE)
            .update({"status": "pending", "processing_started_at": None})
            .eq("status", "processing")
            .lt("processing_started_at", cutoff)
            .execute()
        )

        count = len(resp.data) if resp.data else 0
        if count:
            logger.warning(f"Reset {count} stale job(s) back to pending")
        return count

    except APIError as exc:
        if exc.code in _FATAL_PGRST_CODES:
            raise
        logger.error("reset_stale_jobs failed", exc_info=exc)
        return 0
    except Exception as exc:
        logger.error("reset_stale_jobs failed", exc_info=exc)
        return 0


# ---------------------------------------------------------------------------
# Status updates
# ---------------------------------------------------------------------------


async def update_job_status(
    job_id: str,
    status: str,
    *,
    processed_url: Optional[str] = None,
    error_message: Optional[str] = None,
    processing_time_ms: Optional[int] = None,
) -> None:
    """
    Persist a status transition for *job_id*.

    Keyword-only optional fields (processed_url, error_message,
    processing_time_ms) are included in the payload only when provided,
    so callers never accidentally overwrite existing values with None.

    Raises on DB failure so the caller can handle retry / alerting.
    """
    payload: dict = {
        "status": status,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }

    if processed_url is not None:
        payload["processed_url"] = processed_url
    if error_message is not None:
        payload["error_message"] = error_message
    if processing_time_ms is not None:
        payload["processing_time_ms"] = processing_time_ms

    try:
        get_supabase().table(_TABLE).update(payload).eq("id", job_id).execute()
        logger.info(
            f"Job status → {status}",
            extra={"job_id": job_id, "status": status},
        )
    except Exception as exc:
        logger.error(
            "update_job_status failed",
            extra={"job_id": job_id, "status": status},
            exc_info=exc,
        )
        raise

async def update_product_image_url(product_id: str, processed_url: str) -> None:
    """
    Write the processed image URL back to the ``image_url`` column of the
    product row so downstream callers always find the latest version.

    Raises on DB failure.
    """
    try:
        get_supabase().table(_TABLE).update({"image_url": processed_url}).eq("id", product_id).execute()
        logger.info(
            "Product image_url updated",
            extra={"product_id": product_id, "processed_url": processed_url},
        )
    except Exception as exc:
        logger.error(
            "update_product_image_url failed",
            extra={"product_id": product_id},
            exc_info=exc,
        )
        raise


async def update_product_generated_images(
    product_id: str,
    generated_urls: list[str],
    *,
    update_image_url: bool = True,
) -> None:
    """
    Persist the concurrently generated image variant URLs for a product.

    Writes the ordered list of public image URLs to the
    ``generated_image_urls`` JSONB column on the product row.

    Parameters
    ----------
    product_id : str
        UUID of the product row to update.
    generated_urls : list[str]
        Ordered list of public image URLs (variant 1 → variant 4).
        Empty strings or None values in the list represent variants that
        failed generation; callers should filter these before passing.
    update_image_url : bool
        When True (default), also updates ``image_url`` to the first
        URL in *generated_urls* so existing consumers remain unaffected.
        Pass False to leave ``image_url`` unchanged.

    Raises
    ------
    Exception
        Re-raises any Supabase error so the caller can handle it.
    """
    if not generated_urls:
        logger.warning(
            "update_product_generated_images called with empty list — skipping",
            extra={"product_id": product_id},
        )
        return

    # IMPORTANT: pass the native Python list directly — PostgREST serialises it
    # to a JSON array automatically.  Passing json.dumps() (a Python string)
    # sends a text literal to a JSONB column which PostgREST rejects.
    payload: dict = {
        "generated_image_urls": generated_urls,   # list[str] → JSONB array
    }

    if update_image_url:
        payload["image_url"] = generated_urls[0]

    try:
        resp = get_supabase().table(_TABLE).update(payload).eq("id", product_id).execute()
        logger.info(
            f"Stored {len(generated_urls)} generated image URL(s) for product",
            extra={
                "product_id": product_id,
                "variant_count": len(generated_urls),
                "urls": generated_urls,
                "db_response_count": len(resp.data) if resp.data else 0,
            },
        )
    except Exception as exc:
        logger.error(
            f"update_product_generated_images FAILED — product_id={product_id} urls={generated_urls}",
            extra={"product_id": product_id},
            exc_info=exc,
        )
        raise