name: Sync Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to new repo
        run: |
          git remote add new https://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@github.com/jwellery44-prog/ai-pipeline
          git push new main